### ISSUE TITLE
Zookeeper fails on boot because listening port

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#103]
when zookeeper checks if needed port is free, that check may fail because ESTABLISHED connection using that port. Need filter to check only process LISTEN on it.
This problem may raise when a host has running any process using zookeeper (kafka,hdfs,yarn....) and try to start a zookeeper server.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#17
