### ISSUE TITLE
Flume: Allow multiple flume instances with the same init script.

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#108]
Right now, the init script only run one instance of Flume, with the "agent name" -> "agent"

DEFAULT_FLUME_AGENT_NAME="agent"
FLUME_AGENT_NAME=${FLUME_AGENT_NAME:-${DEFAULT_FLUME_AGENT_NAME}}
...
... --name $FLUME_AGENT_NAME ...

So only we can use the Flume configuration file for one agent.

We can track the issue in BigTop: https://github.com/apache/bigtop/pull/6

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#16
