### ISSUE TITLE
Package logstash-1.4.2_elk-0.0.1-r1 enhanced

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#119]
The package logstash could be enhanced with the following points:
1. Remove the jruby JAR from the package and make a native Centos JRuby RPM package. Reference here https://github.com/bkabrda/jruby.spec.
2. Include  /etc/init.d/logstash-web and rework /etc/init.d/logstash from vendor.
3. Check if we need kibana embedde into logstash package, or we can make a kibana RPM dependencie.
4. Check if the JAR files from vendor GitHub account can be donwloaded from Maven Central or make from the real sources.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#13
