### ISSUE TITLE
[ Storm 0.9.2 - Openbus 0.0.1 ] Storm scripts should use pid file

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#144]
Storm service scripts should create a pid file instead recover it using pgrep.

in the nohub command should include 'echo $!' > "$PIDFILE"
when stop should remove the file
any use of pgrep should use the PIDFILE

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#3
