### ISSUE TITLE
hadoop-fuse-dfs Input/output error

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#20]
$ sudo -E hadoop-fuse-dfs dfs://doop-manager.buildoop.org:8020 /mnt/hdfs-mount/
INFO /home/jroman/HACK/buildoop.git/build/work/hadoop-2.2.0_openbus-0.0.1-r1/rpmbuild/BUILD/hadoop-2.2.0-src/hadoop-hdfs-project/hadoop-hdfs/src/main/native/fuse-dfs/fuse_options.c:164 Adding FUSE arg /mnt/hdfs-mount/

$ ls /mnt/hdfs-mount 
ls: cannot access /mnt/hdfs-mount: Input/output error

**Comment by sonoman** [comment]
Hi ! I'm having this exact problem. Any Ideas ?
This is my fstab line:
hadoop-fuse-dfs#dfs://192.168.80.132:8020 /hdfs fuse allow_other,usetrash,rw 2 0

I know endpoint is allright because I'm using that URI in a Pig program (namenode parameter) and is working fine.

**Comment by javiroman** [comment]
Probably  you don't have libhdfs.so or libjvm.so on your LD_LIBRARY_PATH.

This was my problem, on this bug, ...., i'm going to close it.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#34
