### ISSUE TITLE
hadoop-hdfs-zkfc

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#28]
In start daemon script, installation command has hardcoded user and group, it should refer to previously defined variable $SVC_USER, and maybe declare a new variable $SVC_GROUP

**Comment by jucaf** [comment]
Similar with pid files. Whenever a hadoop service starts, username's user running the service are appended to the pidfile and log, but pidfile are defined without taking into consideration $SVC_USER, so it fails to find process pid.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#33
