### ISSUE TITLE
Enable Hadoop security kerberos and JSVC

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#31]
The DataNode need JSVC in order to run the DN daemon in privileged socket ports. The DN package must be depends on standard packages:

jakarta-commons-daemon-1.0.1-8.9.el6.x86_64
jakarta-commons-daemon-jsvc-1.0.1-8.9.el6.x86_64

However this version has bugs running with hadoop. This is why Bigtop is using his own package: https://issues.apache.org/jira/browse/BIGTOP-389

We have to do the same.

**Comment by javiroman** [comment]
Package added in commit aa9894eff5be55a3c2f17dce349444e59dd17755

This package is pending of testing.

**Comment by javiroman** [comment]
New version of JSVC -> 1.0.13 in commit dc94f91388080af49c9b5fbca99089d34445e466

**Comment by jucaf** [comment]
Tested. It works fine. Thanks

**Comment by javiroman** [comment]
In order to work fine with all this staff is necessary the installation of:

Java Cryptography Extension (JCE) security policy .jars [1] 
The Oracle JDK 1.7 is shipped with limited version of this JCE. So it's neccesary the installation of additional package from [2]

[1] http://en.wikipedia.org/wiki/Java_Cryptography_Extension
[2] http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
