### ISSUE TITLE
Secure datanode stop

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#32]
In hadoop-hdfs-datanode init script  line 103 is
start_daemon -u $SVC_USER $EXEC_PATH --config "$CONF_DIR" stop $DAEMON_FLAGS

but should be

  if [ -n "$HADOOP_SECURE_DN_USER" ]; then
    TARGET_USER=root
  else
    TARGET_USER=${HADOOP_DATANODE_USER:-hdfs}
  fi
  start_daemon -u $TARGET_USER $EXEC_PATH --config "$CONF_DIR" stop $DAEMON_FLAGS

The if statement control if is a secured cluster, if so it uses jsvc which is launched by root not hdfs user

**Comment by javiroman** [comment]
Fixed in commit fd085831ca577c499bb0dccd899fbac18498c640
