### ISSUE TITLE
Create package HUE 3.5.0

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#35]
Create package for HUE_VERSION=3.5.0_openbus-0.0.1-r1

**Comment by jucaf** [comment]
Hue 3.5.0 release doesn't support secured yarn, so it is needed to use a newer version. It is better to use cdh5.0.0-release tag from GitHub, which contains the required functionality and has been stabilized by cloudera.

**Comment by javiroman** [comment]
Shebang  (that is, "#!") at the beginning of a script:

BUILD/hue.git/build/env/bin/hue

Has hardcoded the full path to python2.6 embedded in HUE sources. This line has the problem described in:

http://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel

The problem was fixed for the Buildoop building host changing the version name of the package, which was a few long.

This issue has be taken into account in the future.
