### ISSUE TITLE
service spark-master start -> ERROR 

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#40]
nice: /usr/lib/spark/spark-class: No such file or directory

**Comment by mvalleavila** [comment]
spark-master not starting:

Edit /etc/init.d/spark-master 

```
EXEC_PATH="/usr/lib/spark/bin/spark-class"
```

spark-worker isn't starting too
Edit /etc/init.d/spark-worker 

```
EXEC_PATH="/usr/lib/spark/bin/spark-class"
```

In /etc/spark/conf/spark-env.sh change symbol ` for ' in line export STANDALONE_SPARK_MASTER_HOST=

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#30
