### ISSUE TITLE
Avoid to use Java Cryptography Extension (JCE) in kerberos

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#45]
CentOS/Red Hat Enterprise Linux 5.6 or later uses AES-256 encryption by default for tickets, you must install the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy File on all cluster and Hadoop user machines. This is a ZIP file from Oracle, and it's not package for any distro.

We have to use other encryption by default to avoid this extra-deployment.

**Comment by jucaf** [comment]
In the default Kerberos installation, it's enabled the encryption type aes:256, which is restricted by US exportation laws, so it's necessary to change the file /var/kerberos/krb5kdc/kdc.conf and delete aes256-cts:normal from supported enc types. Then recreate the Kerberos DB.

<code>
# cat /var/kerberos/krb5kdc/kdc.conf
[kdcdefaults]
 kdc_ports = 88
 kdc_tcp_ports = 88
[realms]
 REALM = {
  acl_file = /var/kerberos/krb5kdc/kadm5.acl
  dict_file = /usr/share/dict/words
  admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
  supported_enctypes = aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal
 }
</code>
