### ISSUE TITLE
Create package Sqoop 1.99.3

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#54]
Install phase error:
- install -d -m 0755 /home/jroman/HACK/buildoop.git/build/work/sqoop-1.99.3_openbus-0.0.1-r1/rpmbuild/BUILDROOT/sqoop-1.99.3-openbus0.0.1_1.x86_64/etc/default
- install -d -m 0755 /home/jroman/HACK/buildoop.git/build/work/sqoop-1.99.3_openbus-0.0.1-r1/rpmbuild/BUILDROOT/sqoop-1.99.3-openbus0.0.1_1.x86_64/var/lib/sqoop
- install -m 0644 'dist/target/sqoop-_/client/lib/_.jar' /home/jroman/HACK/buildoop.git/build/work/sqoop-1.99.3_openbus-0.0.1-r1/rpmbuild/BUILDROOT/sqoop-1.99.3-openbus0.0.1_1.x86_64//usr/lib/sqoop/client-lib/
  install: cannot stat `dist/target/sqoop-_/client/lib/_.jar': No such file or directory

**Comment by javiroman** [comment]
The package is ready for testing.

**Comment by javiroman** [comment]
https://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Release-Notes/Sqoop2.html
Sqoop 2 works only in a non-secure cluster
It's required to use sqoop1 in order to support a secure cluster.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#28
