### ISSUE TITLE
HBase package rebuild

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#56]
When try to start hbase it fails with:
java.lang.ClassNotFoundException: org.apache.hadoop.metrics2.lib.MetricMutable
which is a hadoop1.2.1 library:
http://hadoop.apache.org/docs/r1.2.1/api/org/apache/hadoop/metrics2/lib/MetricMutable.html
it's missing in hadoop2.2.0:
http://hadoop.apache.org/docs/r2.2.0/api/org/apache/hadoop/metrics2/lib/package-frame.html
It looks that this class has been renamed to this one:
http://hadoop.apache.org/docs/r2.2.0/api/org/apache/hadoop/metrics2/lib/MutableMetric.html
So a rebuild of package is required

**Comment by javiroman** [comment]
Good point, that's my fault. I'm going to review the package.

**Comment by javiroman** [comment]
Fixed.
