### ISSUE TITLE
Check file owner for each done_intermediate subdirectory

### ISSUE THREAD

**Issue by jucaf** [keedio/buildoop#68]
It should be checked that each subdirectory in done_intermediate has owner equal to it's name. ls should look like this: (dir name = dir owner)

drwxrwx---   - mapred      hadoop  /user/jhs/done_intermediate/mapred
drwxrwx---   - hdfs        hadoop  /user/jhs/done_intermediate/hdfs
drwxrwx---   - testUser hadoop  /user/jhs/done_intermediate/testUser

If this permissions aren't propertly sets, oozie could have problems.

**Comment by javiroman** [comment]
Issue related to file-permission-checker.sh

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#24
