### ISSUE TITLE
Flume-ng-kafka-sink dependencies missing

### ISSUE THREAD

**Issue by mvalleavila** [keedio/buildoop#71]
Following dependencies are not include in /usr/lib/flume/lib

kafka_2.9.2-0.8.0.jar  --> Found in /usr/lib/kafka/
scala-library-2.9.2.jar
metrics-core-3.0.0.jar

**Comment by javiroman** [comment]
This issue is related to #66

**Comment by javiroman** [comment]
The flume kafka sink must be include the file: kafka_2.9.2-0.8.0.jar 

Flume agent run in hosts without kafka libraries installed.
