### ISSUE TITLE
Namenode halts after getting into a deadly loop of UserGroupInformation retries

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#74]
When you deploy your namenode independently from hbase services. The NameNode raise WARNING messages:

WARN org.apache.hadoop.security.UserGroupInformation: No groups available for user hbase

Passed any time the NameNode increase the HEAP size used and end with a uncontrolled crash.

This issue is reported here [1] and here [2]

[1] https://groups.google.com/a/cloudera.org/forum/#!msg/cdh-user/d2e5V3kGqjE/4KzO0wfS_SAJ
[2] http://hortonworks.com/community/forums/topic/hbase-causes-errors-in-namenode-logs/

This issue affect to Hadoop 2.2.0 version.

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#21
