### ISSUE TITLE
Package avro-repo-bundle for  Camus LatestSchemaKafkaAvroMessageDecoder

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#76]
The Camus decoder "LatestSchemaKafkaAvroMessageDecoder" uses a repository avro schema server for its operation.

Whe have to build a package for this feature.

**Comment by javiroman** [comment]
This package is based on: https://github.com/mvalleavila/avro-1.7.4-schema-repo
Forked in Buildoop.

**Comment by mvalleavila** [comment]
The Camus decoder used with the repository avro schema server is "KafkaAvroMessageDecoder" instead of "LatestSchemaKafkaAvroMessageDecoder"

**Comment by javiroman** [comment]
Changed the name of repository to https://github.com/buildoop/avro-schema-repo
