### ISSUE TITLE
bug with oozie 4.4.0 

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#81]
https://issues.apache.org/jira/browse/OOZIE-1314

This problem is fixed in Oozie 4.1.0 and Oozie 4.0.0 patched by Cloudera.

http://archive.cloudera.com/cdh5/cdh/5/oozie-4.0.0-cdh5.0.0-beta-2.releasenotes.html
https://github.com/apache/oozie/blob/master/release-log.txt
http://stackoverflow.com/questions/18979204/can-not-kill-oozie-job-by-kill-command

**Comment by mvalleavila** [comment]
This issue was moved to buildoop/buildoopRecipes#20
