### ISSUE TITLE
Bump version of Storm to 0.9.2

### ISSUE THREAD

**Issue by javiroman** [keedio/buildoop#90]
This bump affect the packages:

STORM_VERSION=0.9.1
STORM-KAFKA_VERSION=0.8.0

and probably:

STORM-HBASE_VERSION=0.9.1.7f79e191ef

**Comment by javiroman** [comment]
Package pushed in commiit 2aba1b9d844d400454986348d7ead83db73b0350
The package is pending to test.

**Comment by javiroman** [comment]
The package must be tested with Kafka, HBase and ES.

**Comment by javiroman** [comment]
Duplicate files:

$ rpm -qf /usr/lib/storm/external/storm-kafka/storm-kafka-0.9.2-incubating.jar
storm-0.9.2-openbus0.0.1_1.noarch
storm-kafka-0.9.2-openbus0.0.1_1.noarch

**Comment by mvalleavila** [comment]
Configuration path not set properly:

Current /etc/storm
Set to /etc/storm/**conf**

**Comment by mvalleavila** [comment]
Remove /usr/lib/storm/external directory from storm rpm package installation. ( Install only in storm-kafka package)

**Comment by mvalleavila** [comment]
Storm supervisor daemon dies when an active topology is killed and can´t start until storm-local dir is removed

**Comment by mvalleavila** [comment]
storm-elastic search package doesn't depends of storm

**Comment by mvalleavila** [comment]
storm kafka doesn't remove simbolic link after package remove
