### ISSUE TITLE
Storm 0.9.2 package tests with storm-kafka native and storm-hbase

### ISSUE THREAD

**Issue by mvalleavila** [keedio/buildoop#96]
Is neccesary to perform some tests of new storm version with the connectors with kafka and hbase.
Also tests between kafka-0.8.1.1 and storm-kafka native connector should be done

**Comment by javiroman** [comment]
dupicated of #90

**Comment by javiroman** [comment]
New packages:

storm-nimbus-0.9.2-openbus0.0.1_1.noarch.rpm
storm-ui-0.9.2-openbus0.0.1_1.noarch.rpm
storm-supervisor-0.9.2-openbus0.0.1_1.noarch.rpm
storm-drpc-0.9.2-openbus0.0.1_1.noarch.rpm
storm-kafka-0.9.2-openbus0.0.1_1.noarch.rpm

Important the new package: storm-kafka-0.9.2-openbus0.0.1_1.noarch.rpm
